spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/apply?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis

server:
  servlet:
    session:
      timeout: 30m
      cookie:
        path: /
    context-path: /apply
  port: 8081



mybatis-plus:
  mapper-locations: classpath*:com/springboot/mapper/*.xml
  type-aliases-package: com.springboot.beans